#!/bin/bash

### This script provides a section.dat (to use with cdftransportiz)
### from the drakkar_sections_table.txt file
### Example : ./create_sections_list ORCA025
#--------------------------------------------------------------
#   $Rev$
#   $Date$
#   $Id$
#--------------------------------------------------------------

if [ $# == 0 ] ; then
    echo ' USAGE: create_sections_list CONFIG '
    exit 0
fi

CONFIG=$1

### Transports along sections :

grep -e" $CONFIG " drakkar_sections_table.txt  > temp.txt

linebeg=1 
lineend=`wc -l temp.txt | awk '{print $1}' `

lines=''
n=$linebeg

\rm -f section.dat # remove (if any)

while (( $n <= $lineend )) ; do

  line=` sed -n ${n},${n}p temp.txt `
  section=` echo $line | awk '{print $1}' `
  indices=` echo $line | awk '{print $3 " " $4 " " $5 " " $6}' `
  varnam=$( grep -e "$section" drakkar_sections_table.txt | head -1 |  awk '{print $2 }' )
  secnam=$( grep -e "$section" drakkar_sections_table.txt | head -1 | awk '{print $3 }' )

  echo $section $varnam $secnam   >> section.dat
  echo $indices  >> section.dat

  n=$(( n + 1 ))
done

echo 'EOF'  >> section.dat
\rm -f temp.txt

### Transports in sigma classes :

grep -e " $CONFIG " drakkar_trpsig_table.txt  > temp.txt

linebeg=1
lineend=`wc -l temp.txt | awk '{print $1}' `

lines=''
n=$linebeg


\rm -f dens_section.dat # remove (if any)

while (( $n <= $lineend )) ; do

  line=` sed -n ${n},${n}p temp.txt `
  section=` echo $line | awk '{print $1}' `
  indices=` echo $line | awk '{print $3 " " $4 " " $5 " " $6}' `
  varnam=$( grep -e "$section" drakkar_trpsig_table.txt | head -1 |  awk '{print $2 }' )
  secnam=$( grep -e "$section" drakkar_trpsig_table.txt | head -1 | awk '{print $3 }' )
  echo $section $varnam $secnam   >> dens_section.dat
  echo $indices  >> dens_section.dat

  n=$(( n + 1 ))
done

echo 'EOF'  >> dens_section.dat
\rm -f temp.txt

