#!/bin/ksh
#jade -N zyrly_<year>
#jade -l select=1:ncpus=8:mpiprocs=8
#jade -l walltime=1:30:00
#jade -l cluster=hpt
#jade -W depend=afterok:<JOBIDMOY>:<JOBIDVT>
##jade -mb -me
#jade -v NB_NODES=1,NB_NPROC=12

#vayu -N zyrly_<year>
#vayu -l ncpus=1
#vayu -l walltime=1:30:00
#vayu -W depend=afterok:<JOBIDMOY>:<JOBIDVT>

set -x
CONFIG=<CONFIG>
CASE=<CASE>

CONFCASE=${CONFIG}-${CASE}
CTL_DIR=<WPDIR>

#. $HOME/.profile
cd $CTL_DIR
. ./config_moy.ksh
#
./mvcalmoy.ksh <year>


