# Makefile used to clean the local dir from ~ 
#  and to create links for scripts to be used at legi or lpo
#  $Rev$
#  $Date$
#  $Id$
#--------------------------------------------------------------


clean:
	@-\rm -f *~

legi: clean
	ln -sf monitor_legi.csh monitor.csh

lpo: clean
	ln -sf monitor_lpo.csh monitor.csh
