# Makefile used to clean the local dir from ~ 
#  and to create links for scripts to be used at legi or lpo
#  $Rev$
#  $Date$
#  $Id$
#--------------------------------------------------------------


clean:
	@-\rm -f *~

legi: clean
	ln -sf c-monitor_legi.csh c-monitor.csh
	ln -sf c-monitor3_legi.csh c-monitor3.csh
	ln -sf c-monitor4_legi.csh c-monitor4.csh

lpo: clean
	ln -sf c-monitor_lpo.csh c-monitor.csh
	ln -sf c-monitor3_lpo.csh c-monitor3.csh
	ln -sf c-monitor4_lpo.csh c-monitor4.csh
